import { 
  Heart, 
  Frown, 
  ShoppingBag, 
  Target, 
  User, 
  Settings, 
  Sparkles, 
  Camera, 
  FileText, 
  Share2, 
  Plus, 
  X, 
  ChevronRight, 
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Save, 
  Home, 
  FlaskConical, 
  Info,
  Edit3,
  RefreshCw,
  MoreHorizontal,
  Brain,
  Coffee,
  MessageCircle,
  Cloud,
  Dices,
  Calendar,
  PenTool,
  BookOpen,
  Music,
  Film,
  Layers,
  Box,
  CheckCircle,
  Zap,
  MapPin,
  Star,
  CreditCard,
  Users,
  Download,
  RotateCcw,
  Trophy,
  Bell,
  Moon,
  HelpCircle,
  Shield,
  LogOut,
  Clock, 
  Trash2, 
  Share,
  // New MBTI Icons
  Feather,
  Briefcase,
  Palette,
  Rocket,
  Anchor,
  Compass,
  Mountain,
  Sun,
  Crown,
  Lightbulb,
  CloudRain
} from 'lucide-react';

export {
  Heart, Frown, ShoppingBag, Target, User, Settings, Sparkles, Camera,
  FileText, Share2, Plus, X, ChevronRight, ChevronLeft, ChevronDown, ChevronUp, Save, Home, FlaskConical,
  Info, Edit3, RefreshCw, MoreHorizontal,
  Brain, Coffee, MessageCircle,
  Cloud, Dices, Calendar, PenTool,
  BookOpen, Music, Film, Layers, Box, CheckCircle, Zap, MapPin,
  Star, CreditCard, Users, Download, RotateCcw, Trophy,
  Bell, Moon, HelpCircle, Shield, LogOut,
  Clock, Trash2, Share,
  // Export new icons
  Feather, Briefcase, Palette, Rocket, Anchor, Compass, Mountain, Sun, Crown, Lightbulb, CloudRain
};